### ISSUE TITLE
Set a data member on toggle

### ISSUE THREAD

**Issue by tokejepsen** [pyblish/pyblish-qml#125]
When a user toggles the enable state in the UI, this only gets reflected in which plugins to process.

The idea is to set some data member on the asset, to indicate the enable state in the UI. Think the suggested data member was to modify the "published" data member, but I might be wrong @mottosso?

**Comment by mottosso** [comment]
The toggled state will modify the `publish` data member, where `__published__` might become another variable indicating whether an `Instance` has already been published.

**Comment by tokejepsen** [comment]
So to add further info for this, heres from gitter;

tokejepsen 12:05
So if I do a change to the context I get from self.host.context(), will this be reflected when publishing from the UI?
Or will it just get a fresh new context from the host prior to publishing?

mottosso 12:10
No, it's a one-way street. The context is created in the host, and sent across when you refresh.
To make a change, you'll need to build a new street, where information can go from QML to the host.
There was an implementation of this early on that never got finished, maybe it can be helpful here.
https://github.com/pyblish/pyblish-qml/blob/4d3a69778283b061f5697e3d3b7fc0a8ea815964/pyblish_qml/control.py#L428
The idea was that, whenever a particular item in the model changed, such as it's checked state, QML would emit this change to the host, which would in turn apply it to the instance or plug-in.
[This](https://github.com/pyblish/pyblish-rpc/blob/436ea351387c5159acb0fc06120d341dc97a6df7/pyblish_rpc/client.py#L18) is the object you access from self.host. You could add a method there called "save" which would call the remote host via [this](https://github.com/pyblish/pyblish-rpc/blob/436ea351387c5159acb0fc06120d341dc97a6df7/pyblish_rpc/service.py#L23). Then this is where you are basically inside of Nuke/Maya etc. and can modify the actual instances and plug-ins.

mottosso 12:17
You can think of [```pyblish_rpc.client```](https://github.com/pyblish/pyblish-rpc/blob/436ea351387c5159acb0fc06120d341dc97a6df7/pyblish_rpc/client.py#L18) and the [```pyblish_rpc.service```](https://github.com/pyblish/pyblish-rpc/blob/436ea351387c5159acb0fc06120d341dc97a6df7/pyblish_rpc/service.py#L23) as the Remote and Local borders, they have a 1-1 mapping between their methods and properties and handle the translation between the two borders.
.client runs in QML, and .service runs locally within the host.
You're entering the realm of IPC, it can be a bit daunting. 

tokejepsen 12:19
So is nothing saved or stay in memory between refreshes of the UI?

mottosso 12:20
No, nothing

**Comment by tokejepsen** [comment]
This also means this issue can tackle the problem of the state of the scene not being saved between refreshes of the UI, which is mentioned [here](http://forums.pyblish.com/t/quick-toggles/155/2?u=tokejepsen)

**Comment by tokejepsen** [comment]
Had some more thoughts about this. If/When this feature and the subsequent feature of saving the state of the instance to the scene, we will need to introduce exactly that as an attribute on an instance; state.

Currently when you discover an instance in the scene, you add it to the context, and if an instances criteria for being ready to publish (state) isn't there, you usually just reframe from adding it to the context and thus not visible when publishing.
If we introduced a state to instances (active/deactive), you could add all the instances discovered in the scene, and let the user choose in the UI which instances to publish.

**Comment by mottosso** [comment]
`state` already exists, it's called `publish`. If you set this, it will de-toggle the instance from the GUI. I would expect toggling it back to alter this attribute. Is that what you mean?

**Comment by tokejepsen** [comment]
Yeah, its then just a matter of adding all instances to the context. Even the ones that have ```publish``` set to ```False```.

**Comment by mottosso** [comment]
That's what's happening currently. :)

Really all we need is for the QML GUI to write the value of it somewhere persistent.

For example, if the value is coming from an attribute `publish` on an Object Set, then the QML GUI would need to change that value, such that when it collects next time, it will pick up the new value.

If there is no attribute, then maybe it could make one, and always attempt to read from it.

**Comment by tokejepsen** [comment]
Got all caught up in the callbacks, that I completely forgot about this. Now the question is whether changing the ```publish``` data member, this is responsibility of callbacks or pyblish-qml?

If an instance doesn't have a callback, the published state won't presist between resets, but that is expected since the scene hasn't changed. It is still useful to know whether an instance needs to be processed within a GUI session.

**Comment by mottosso** [comment]
Well, I think, like we talked about, we could have two levels of persistance here.

1. Physically change the instance in the host, such that the new status picked up on next refresh.
2. Remember the visual items and their state locally in QML.

For (1), I can't say for sure, but would it be possible to assign this responsibility to pyblish-integration? Instances and accessing them is the same across hosts, so we might get lucky and only have to do it once; as opposed to once per integration.

For (2), the challlenge is keeping track of state *per host*. There is already an indicator of hosts, used previously to keep track of timeouts and heartbeats. Technically it would mean just storing check state along with each host in a dictionary, and reassigning it upon reset.

Then the questions is, when both are persisted, who wins? And I think it's quite simply the state from QML, in which case the state within the instance is primarily used for first connect, and in by users in plug-ins and such.

What do you think?

**Comment by mottosso** [comment]
On second though, no, we can't get an all-in-one persistence in the host because it would depend on how instances are collected, right?

I would start with QML persistence, and make it really easy to write the callback capable of persisting in a host.

Packages like Magenta could then come with one built-in.

**Comment by tokejepsen** [comment]
I've got it working with persistence into the host, with callbacks.

The problem comes when I have a plugin that wants to query the ```publish``` attribute of an instance. I'll give a breakdown of the situation I'm experiencing;

1. An instance is toggled on.
2. User untoggles the instance, and a callback ensures this state persists to the host.
3. User publishes with a plugin that queries the context whether some instances have ```publish``` set to ```True```.
4. The plugin finds the instance that was untoggled because the pyblish-qml session hasn't been reset, and so haven't gotten the updated state of instance, that the callback persisted in the host. Further pyblish-qml has not set the ```publish``` attribute to ```False```, hence why to pyblish-qml the instance is still toggled on for publishing.

A bit of a unique situation, but still a motivation to change the data member ```publish``` state to reflect what is happening in the GUI.

**Comment by mottosso** [comment]
Ah, yes good point.

Looks like there's three occurrences of persisting data from the GUI.

1. In QML only
2. In current Instances
3. In host

For (2) I think this is a good spot for pyblish-integration. It could just alter the live instances via the current context, shouldn't be too difficult.

And (3) is still custom and dependent on the developer and his collectors.

**Comment by tokejepsen** [comment]
> For (2) I think this is a good spot for pyblish-integration. It could just alter the live instances via the current context, shouldn't be too difficult.

Sorry, I don't quite get number 2. From what I described I can only see two place where you need to set some data; GUI and host.

**Comment by mottosso** [comment]
(2) would alter the instance that is currently active in the context.

E.g.

```python
context["myInstance"].data["publish"] = True
```

It would enable you to query that from plug-ins; without resetting.

(3) Would physically write to Maya, like a `.publish` attribute on a node, such that it would get picked up during next reset. This would actually persist across resets.

**Comment by tokejepsen** [comment]
> It would enable you to query that from plug-ins; without resetting.

Alright:) Now I don't get what you mean with number 1? Do you mean that it visually changes for the user?

**Comment by mottosso** [comment]
:) I'll try and break it down. There are three properties we want, A, B and C, and 3 methods with which to achieve it, 1-3.

|                                   | QML (1) | In-Memory (2)      | Host (3)
|----------------------------|------------|------------------------|-----------
| A) Persistent              |               |                              | X
| B) Query via plug-ins |               | X                           |
| C) GUI remembers    | X            |                              | X

To achieve A), we would need to physically alter the scene. As an example, if you use an ObjectSet as an instance in Maya, where the publishable attribute is determined by a Maya-attribute `publish`, persistence means to physically alter that value such that it can be saved with the scene.

For B), all we really need is for the GUI so alter the instances currently in memory. Once you hit reset, a Context is created and populated with Instances. Currently, when you toggle an item, those instances are not affected, thus when you query the `publish` data-member, it won't reflect the current state in the GUI.

C) Means that regardless of whether the in-memory instances or the host remembers the `publish` setting, it will remember the toggled state in the GUI such that when you hit "Refresh" the `publish` attribute will first get read from the scene and stored in each Instance, and *then* toggled to whatever state they were in during the last reset by the GUI; just as though a human were to do it.

C) is useful in cases where you toggle something and reset; currently whatever you toggled will have to be re-toggled because the GUI forgets so easily.

For C), you'll notice that we get a GUI that remembers if we already have host persistence. Which brings into question which state to listen to, should they differ.

Does it make more sense now? We need all of these things to cover all bases.

**Comment by mottosso** [comment]
This should be implemented by now!
