### ISSUE TITLE
Environment can only contain strings

### ISSUE THREAD

**Issue by mottosso** [pyblish/pyblish-qml#238]
### Problem

If a user has manually modified `os.environ` from within Python using anything other than strings, the environment cannot be forwarded to `subprocess.Popen` resulting in an exception.

**Example**

```python
import os

# Wrong
os.environ["MY_NUMBER"] = 5

# Right
os.environ["MY_NUMBER"] = "5"
```

### Solution

We cannot protect against what is inserted into `os.environ` as it is a plain dictionary with no type checking. We can however limit which portion of it we require the end user to treat well.

**Comment by darkvertex** [comment]
By the way it's an issue with Unicode strings too. Basically anything not the "str" type.

You have to be extra careful with Maya because maya.cmds always returns Unicode and pymel will too when returning any string values, so if you blindly take stuff from the API into is.environ, you'll be in trouble later.

At work I found some very old sloppy code that was putting Unicode in our is os.environ in the userSetup.py and it had not been an issue (yet!) so I never noticed until I started using pyblish-qml which warned me about my bad environment.

**Comment by hannesdelbeke** [comment]
maya 2019 (python2.7) does not allow this to run:
```python
import os
os.environ["MY_NUMBER"] = 5
# # Error: TypeError: file C:\Program Files\Autodesk\Maya2019\bin\python27.zip\os.py line 422: must be string, not int # 
```

it does allow this to run but Pyblish appears to still work. both GUI and commandline
```python
os.environ["TEST"] = u'test'
````

**Comment by BigRoy** [comment]
The issue is with `unicode` vs `str` in Py2 I believe. That I have seen which indeed produces subprocess issues. However I have never seen an actual `int` in `os.environ` because Python simply disallows it.

**Comment by mottosso** [comment]
This has actually already been solved, by only importing parts of the environment that QML cares about.

https://github.com/pyblish/pyblish-qml/blob/103fef81938a8e4102dda831898d80c0ac2ba8de/pyblish_qml/ipc/server.py#L143

As for a reproducible, I can't remember where I got the int-case above; unicode is where I remember the production issues were. But, this shouldn't/couldn't be an issue at the moment. At least I haven't heard of any.

If anyone is still having issues, feel free to reopen this issue!
