### ISSUE TITLE
Qt.WindowStaysOnTopHint been overrided

### ISSUE THREAD

**Issue by davidpower** [pyblish/pyblish-qml#252]
Hi.
Since that pyblish-qml gui could not be any other windows's child window, so I thought at least it could be on top, and I found this.

```python
# pyblish_qml/app.py
# ... line 146
		if os.name == "nt":
			# Work-around for window appearing behind
			# other windows upon being shown once hidden.
			previous_flags = window.flags()
			window.setFlags(previous_flags | QtCore.Qt.WindowStaysOnTopHint)
			window.setFlags(previous_flags)
# ...
```
Last line `window.setFlags(previous_flags)` override the `WindowStaysOnTopHint` flag,
is this on purpose ?

Thanks !
btw, really grate work 👍 
this is art, Mr. white

**Comment by mottosso** [comment]
Well spotted! Would you be interested in making a pull request for this?

**Comment by mottosso** [comment]
Or actually no! This is the intended look.

I should have made a better note of it, this is essentially a "hack" required under Windows in order to restore the Window. By first making it stay on top, and then removing it.

That is I think what I meant by that comment, but it isn't very clear. And we almost removed it! I'll improve that note, but still, well spotted!
