### ISSUE TITLE
Customizable menus for validate and publish

### ISSUE THREAD

**Issue by davidmartinezanim** [pyblish/pyblish-qml#33]
I suppose that this will be an easy one.

Is it possible to get rid of the menus validate and publish that we get by default and implement our own. For example, in my case, I would rather not have anything that runs on the command line as it is not user friendly for a lot of the artists. Because of that, I would only leave the one that runs the UI.

In addition to that, I'd like to have a menu somewhere else on my interface so we can keep it organized along with some other tools that we have in-house.

If any of the information is unclear, let me know and I will try to elaborate

**Comment by tokejepsen** [comment]
As far as I know this is more down to the individual extensions, but its a good question for Nuke as well.

Maybe we should keep to one "Publish" menu item under "File", which changes depending on whether you have the frontend installed or not. Then another menu (submenu?) for the more advanced stuff.

**Comment by davidmartinezanim** [comment]
This might work as the default behaviour but I'd also like to be able to disable the default menu and create my own in our *custom tools place*.

**Comment by mottosso** [comment]
This is based on which integration you are referring to, as it is the integration which is responsible for adding anything to a host, like menu items.

In the case of Maya, yes you can. At the moment, the default installation will advise you to run:

```python
import pyblish_maya
pyblish_maya.setup()
```

Which does a few a few things.

1. Add menu items
1. Is the GUI installed?
1. If so, add option-box

If you already know that the GUI will be installed, you can simplify things and replace the above with:

```python
import pyblish_maya
pyblish_maya.setup_endpoint()
pyblish_maya.setup_frontend()
pyblish_maya.register_plugins()
```

Which will put Maya in the same state as with `setup()`, but without adding to the file-menu. From then on, once you call `show()`, the GUI will appear like normal.

```python
pyblish_maya.show()
```

**Comment by davidmartinezanim** [comment]
Fantastic! Just was I was looking for!
I will give it a go

**Comment by mottosso** [comment]
Feel free to close this issue if this solves your problem. :)

**Comment by davidmartinezanim** [comment]
It does for Maya but I'm wondering if @tokejepsen wants to keep it open. I will close it and if he thinks it should be reopen, he can do that.  :-)

**Comment by mottosso** [comment]
Ah yes, you're right, I may have jumped the gun.

Let's come up with suggestions about how we can make this process more intuitive, with potential options and such.

```python
# How about?
import pyblish_maya
pyblish_maya.setup(menu=False)
```

**Comment by davidmartinezanim** [comment]
+1

I think that having something like the code above looks like a better
option than the hack. In addition to that, maybe we just need to make clear
what triggers the interface regardless of the existence of the menu so
people know how to do their own implementation.

**Comment by tokejepsen** [comment]
that does sound good to me, I'm not even sure the default implementation of
the Nuke menu items is how I want it here but it works by default.

**Comment by mottosso** [comment]
> I think that having something like the code above looks like a better option than the **hack**.

I don't think it's fair to consider it a hack, but rather to consider the included mechanisms as "defaults" and everything else as "proper". :)

> In addition to that, maybe we just need to make clear what triggers the interface regardless of the existence of the menu so people know how to do their own implementation.

Sure, good idea.

## Short Version

[Pyblish QML][qml] requires that [Pyblish Endpoint][endpoint] is running from wherever it is launched.

## Long Version

The current GUI, [Pyblish QML][qml], runs as an external process to Maya. Because it is external, we can't get direct access to it via things like Qt signals and slots. Instead, we must tell Maya to "listen" for requests coming from the GUI. This listener is called [Pyblish Endpoint][endpoint].

### Ears And Mouths

Similar to how people have both ears and mouths, Endpoint provides Maya with both which means that it and our GUI can have meaningful conversations. Much like they would automatically have if they were native Python scripts.

Endpoint puts an ear and a mouth on Maya, and without it our GUI *could* speak to it, but Maya refuse to neither *hear* nor *talk* (like an old married couple), so for the GUI to work, we'll need Endpoint.

```python
import pyblish_endpoint
pyblish_endpoint.server.start_production_server(...)
```

Endpoint asks for two things; a `Service` and a `port`.

The port between Endpoint and QML must match, as it is at this number - or "*frequency*" - that communication will take place.

The `Service` on the other hand is an abstraction of everything Endpoint is able to *hear* and *say*, and therefore everything that Maya and our GUI can possibly say to each other.

### A Small Vocabulary

You can think of it as their *entire* vocabulary. Or, as the inputs and ouputs of a Node in Maya, Nuke or Houdini.

```python
 _________      _________      _________ 
|         |    |         |    |         |
|         |    |         |    |         |
|  Host   o----o Service o----o   GUI   |
|         o----o         o----o         |
|         o----o         o----o         |
|_________|    |_________|    |_________|
```

In which Maya, or whatever the host, plugs into one side, and the GUI plugs in to the other.

To satisfy this need, we'll need to:

```python
import pyblish_endpoint
import pyblish_endpoint.service

service = pyblish_endpoint.service.EndpointService
pyblish_endpoint.server.start_production_server(12345, service)
```

### To Walk And Chew Gum

However, because we would like to be able to "*walk and chew gum at  the same time*", we can't simply start listening and forget about all other troubles. This would block the host.

To work around this, we tell it to spend its time listening in a separate *thread*.

```python
def server():
    pyblish_endpoint.server.start_production_server(12345, service)

worker = threading.Thread(target=server)
worker.deamon = True  # Kill thread when parent thread is killed
worker.start()
```

### Don't Be A Stranger

The final piece of the puzzle is to customise the vocabulary, or `Service`.

Because some hosts have particular requirements when it comes to being told what to do from a separate thread, these host must modify the vocabulary such that it conforms to whatever is required of it.

In the case of Maya and Nuke, neither of them likes having some foreign thread tell them what to do, we need to change the vocabulary of Endpoint to respect this.

```python
# This..

class EndpointService(object):
    def process(self, *args, **kwargs):
        ...

# Becomes this..

class MayaService(pyblish_endpoint.service.EndpointService):
    def process(self, *args, **kwargs):
        # Do whatever it is that you do, but do first pass it through this utility function.
        return utils.executeInMainThreadWithResult(
            super(MayaService, self).process, *args, **kwargs)
```

### Conclusion

Here is a complete example of how all of this ties together for the integration in Maya.

```python
import os
import threading
import pyblish_endpoint
import pyblish_endpoint.service
import pyblish_maya.version

from maya import utils

class MayaService(pyblish_endpoint.service.EndpointService):
    def init(self, *args, **kwargs):
        return utils.executeInMainThreadWithResult(
            super(MayaService, self).init, *args, **kwargs)

    def process(self, *args, **kwargs):
        return utils.executeInMainThreadWithResult(
            super(MayaService, self).process, *args, **kwargs)

    def versions(self):
        """Augment version information

        In addition to all other version information,
        include the version number of Pyblish Maya.

        """
        versions = super(MayaService, self).versions()
        versions["pyblish-maya"] = pyblish_maya.version.version
        return versions

def server():
    pyblish_endpoint.server.start_production_server(12345, MayaService)

worker = threading.Thread(target=server)
worker.deamon = True  # Kill thread when parent thread is killed
worker.start()

# Whichever port you choose to listen on, pass this information
# along to an environment variable that a GUI can then ask for
os.environ["ENDPOINT_PORT"] = 12345

print "pyblish: Endpoint running @ %i" % 12345
```


[endpoint]: https://github.com/pyblish/pyblish-endpoint
[qml]: https://github.com/pyblish/pyblish-qml

**Comment by mottosso** [comment]
Feel free to reopen if it's still an issue.
