### ISSUE TITLE
Horizontal scrollbar in the Terminal

### ISSUE THREAD

**Issue by davidmartinezanim** [pyblish/pyblish-qml#49]
Is it worth adding an horizontal scrollbar in the terminal apart from a vertical one? That would prevent lines from jumping down (which sometimes makes difficult to read the output).

**Comment by mottosso** [comment]
I did consider this and had a quick play with it, but personally found it too cumbersome. When the time is right, I think this would make for a great option to have in a "Settings"-style page of the GUI, so that users could pick and choose. It'd remain persistent on a per-user basis, just like in https://github.com/pyblish/pyblish/issues/154

Until then, would resizing the window be an ok alternative?

**Comment by mottosso** [comment]
No longer necessary, as there is word-wrapping and proper formatting of docstrings, log and exception messages as of 0.2.7
